FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY packages/db/prisma ./packages/db/prisma
COPY prisma.config.ts ./
CMD ["npx", "prisma", "migrate", "deploy", "--schema=./packages/db/prisma/schema.prisma"]
